const ACTION_LABELS: Record<string, string> = {
  LOGIN: "Sisteme Giriş",
  LOGOUT: "Sistemden Çıkış",
  PATIENT_CREATE: "Hasta Kaydı Oluşturuldu",
  PATIENT_UPDATE: "Hasta Bilgisi Güncellendi",
  PATIENT_DELETE: "Hasta Kaydı Silindi",
  PATIENT_DATA_EXPORT: "Hasta Verisi Dışa Aktarıldı",
  PATIENT_CONSENT_CREATE: "Hasta Onamı Kaydedildi",
  PATIENT_CONSENT_VOID: "Hasta Onamı İptal Edildi",
  APPOINTMENT_CREATE: "Randevu Oluşturuldu",
  APPOINTMENT_UPDATE: "Randevu Güncellendi",
  APPOINTMENT_DELETE: "Randevu Silindi",
  APPOINTMENT_STATUS: "Randevu Durumu Güncellendi",
  APPOINTMENT_CANCEL: "Randevu İptal Edildi",
  BOOKING_REQUEST_UPDATE: "Online Randevu Talebi Güncellendi",
  PUBLIC_BOOKING_REQUEST_CREATE: "Online Randevu Talebi Oluşturuldu",
  WAITLIST_CREATE: "Bekleme Listesi Oluşturuldu",
  WAITLIST_UPDATE: "Bekleme Listesi Güncellendi",
  WAITLIST_DELETE: "Bekleme Listesi Silindi",
  DOCTOR_BLOCK_CREATE: "Hekim Blokajı Oluşturuldu",
  DOCTOR_BLOCK_DELETE: "Hekim Blokajı Silindi",
  EXAM_CREATE: "Muayene Kaydı Oluşturuldu",
  EXAM_UPDATE: "Muayene Kaydı Güncellendi",
  EXAM_DELETE: "Muayene Kaydı Silindi",
  EXAM_SETTINGS_UPDATE: "Muayene Ayarı Güncellendi",
  TREATMENT_PLAN_CREATE: "Tedavi Planı Oluşturuldu",
  TREATMENT_PLAN_UPDATE: "Tedavi Planı Güncellendi",
  TREATMENT_PLAN_DELETE: "Tedavi Planı Silindi",
  TREATMENT_TYPE_CREATE: "Tedavi Türü Oluşturuldu",
  TREATMENT_TYPE_UPDATE: "Tedavi Türü Güncellendi",
  TREATMENT_TYPE_DELETE: "Tedavi Türü Silindi",
  PRESCRIPTION_CREATE: "Reçete Oluşturuldu",
  PRESCRIPTION_DELETE: "Reçete Silindi",
  PAYMENT_CREATE: "Tahsilat Kaydı Oluşturuldu",
  PAYMENT_UPDATE: "Tahsilat Kaydı Güncellendi",
  PAYMENT_DELETE: "Tahsilat Kaydı İptal Edildi",
  PAYMENT_VOID: "Tahsilat Kaydı İptal Edildi",
  KASA_PAYMENT_CREATE: "Kasa Tahsilatı Oluşturuldu",
  GIDER_CREATE: "Gider Kaydı Oluşturuldu",
  GIDER_UPDATE: "Gider Kaydı Güncellendi",
  GIDER_DELETE: "Gider Kaydı İptal Edildi",
  TAKSIT_MARK_OVERDUE: "Taksit Gecikme Durumu Güncellendi",
  TAKSIT_ODEME: "Taksit Ödemesi Alındı",
  TAKSIT_PLAN_CREATE: "Taksit Planı Oluşturuldu",
  TAKSIT_PLAN_UPDATE: "Taksit Planı Güncellendi",
  TAKSIT_PLAN_DELETE: "Taksit Planı Silindi",
  FIRMA_CREATE: "Firma Kaydı Oluşturuldu",
  FIRMA_UPDATE: "Firma Kaydı Güncellendi",
  FIRMA_KONTAKT_CREATE: "Firma Yetkilisi Eklendi",
  FIRMA_KONTAKT_UPDATE: "Firma Yetkilisi Güncellendi",
  FIRMA_KONTAKT_DELETE: "Firma Yetkilisi Silindi",
  FIRMA_ISLEM_CREATE: "Firma Cari Hareketi Oluşturuldu",
  FIRMA_ISLEM_UPDATE: "Firma Cari Hareketi Güncellendi",
  FIRMA_ISLEM_CANCEL: "Firma Cari Hareketi İptal Edildi",
  PURCHASE_CREATE: "Satın Alma Kaydedildi",
  PURCHASE_UPDATE: "Satın Alma Güncellendi",
  PURCHASE_CANCEL: "Satın Alma İptal Edildi",
  EXPENSE_CATEGORY_CREATE: "Gider Türü Oluşturuldu",
  EXPENSE_CATEGORY_UPDATE: "Gider Türü Güncellendi",
  PRICE_CREATE: "Fiyat Kaydı Oluşturuldu",
  PRICE_UPDATE: "Fiyat Kaydı Güncellendi",
  PRICE_DELETE: "Fiyat Kaydı Silindi",
  STOCK_ITEM_CREATE: "Stok Kartı Oluşturuldu",
  STOCK_ITEM_UPDATE: "Stok Kartı Güncellendi",
  STOCK_MOVEMENT: "Stok Hareketi Kaydedildi",
  STOCK_ITEM_DELETE: "Stok Kartı Pasifleştirildi",
  PROFILE_UPDATE: "Profil Güncellendi",
  PASSWORD_CHANGE: "Şifre Değiştirildi",
  SETTINGS_UPDATE: "Sistem Ayarı Güncellendi",
  STAFF_CREATE: "Personel Eklendi",
  STAFF_UPDATE: "Personel Güncellendi",
  STAFF_DEACTIVATE: "Personel Pasife Alındı",
  POS_CREATE: "POS Cihazı Eklendi",
  POS_UPDATE: "POS Cihazı Güncellendi",
  POS_DELETE: "POS Cihazı Silindi",
  SUPPORT_CREATE: "Destek Talebi Oluşturuldu",
  SUPPORT_UPDATE: "Destek Talebi Güncellendi",
  SUPPORT_DELETE: "Destek Talebi Silindi",
  SMS_TEMPLATE_UPDATE: "SMS Şablonu Güncellendi",
  SMS_TEMPLATE_SAVE: "SMS Şablonu Kaydedildi",
  SMS_TEMPLATE_CUSTOM_SAVE: "SMS Şablonu Kaydedildi",
  SMS_TEMPLATE_CUSTOM_RESET: "SMS Şablonu Varsayılana Döndürüldü",
  SMS_BILGI: "Bilgilendirme SMS'i Gönderildi",
  SMS_HATIRLATMA: "Hatırlatma SMS'i Gönderildi",
  SMS_ANKET: "Değerlendirme SMS'i Gönderildi",
  SMS_TOPLU: "Toplu SMS Gönderildi",
  SMS_BILGI_AUTO: "Otomatik Bilgilendirme SMS'i Gönderildi",
  SMS_REMINDER_AUTO: "Otomatik Hatırlatma SMS'i Gönderildi",
  SMS_BILGI_FAILED: "Bilgilendirme SMS'i Gönderilemedi",
  SMS_HATIRLATMA_FAILED: "Hatırlatma SMS'i Gönderilemedi",
  SMS_ANKET_FAILED: "Değerlendirme SMS'i Gönderilemedi",
  SMS_TOPLU_FAILED: "Toplu SMS Gönderilemedi",
  SMS_BILGI_AUTO_FAILED: "Otomatik Bilgilendirme SMS'i Gönderilemedi",
  SMS_REMINDER_AUTO_FAILED: "Otomatik Hatırlatma SMS'i Gönderilemedi",
  LAB_ORDER_CREATE: "Laboratuvar İşi Oluşturuldu",
  LAB_ORDER_UPDATE: "Laboratuvar İşi Güncellendi",
  LAB_ORDER_RPT_REOPEN: "Laboratuvar İşi Tekrar Açıldı",
  LAB_ORDER_INVOICE_CREATE: "Laboratuvar Faturası Eklendi",
  LAB_TRIP_CREATE: "Laboratuvar Gönderimi Eklendi",
  LAB_TRIP_UPDATE: "Laboratuvar Gönderimi Güncellendi",
  DOCUMENT_CREATE: "Belge Yüklendi",
  DOCUMENT_DELETE: "Belge Silindi",
  MESSAGE_CREATE: "Klinik İçi Mesaj Gönderildi",
  MESSAGE_UPDATE: "Klinik İçi Mesaj Güncellendi",
  MESSAGE_DELETE: "Klinik İçi Mesaj Silindi",
  ANNOUNCEMENT_CREATE: "Duyuru Oluşturuldu",
  ANNOUNCEMENT_DELETE: "Duyuru Silindi",
  CLINIC_TASK_CREATE: "Görev Oluşturuldu",
  CLINIC_TASK_UPDATE: "Görev Güncellendi",
  CLINIC_TASK_DELETE: "Görev Silindi",
  REMINDER_CREATE: "Hatırlatma Oluşturuldu",
  REMINDER_UPDATE: "Hatırlatma Güncellendi",
  REMINDER_DELETE: "Hatırlatma Silindi",
  TWO_FACTOR_ENABLE: "İki Aşamalı Doğrulama Açıldı",
  TWO_FACTOR_DISABLE: "İki Aşamalı Doğrulama Kapatıldı",
  PROFILE_2FA_SETUP_START: "İki Aşamalı Doğrulama Kurulumu Başlatıldı",
  FOLLOW_UP_TYPES_UPDATE: "Hasta Takip Türleri Güncellendi",
  PATIENT_FOLLOW_UP_CREATE: "Hasta Takip Kaydı Oluşturuldu",
  PATIENT_FOLLOW_UP_UPDATE: "Hasta Takip Kaydı Güncellendi",
  PATIENT_FOLLOW_UP_DELETE: "Hasta Takip Kaydı Silindi",
  PATIENT_FOLLOW_UP_EVENT_CREATE: "Hasta Takip Notu Eklendi",
  PATIENT_FOLLOW_UP_EVENT_UPDATE: "Hasta Takip Notu Güncellendi",
  PATIENT_FOLLOW_UP_EVENT_DELETE: "Hasta Takip Notu Silindi",
  CONSENT_TEMPLATE_CREATE: "Onam Şablonu Oluşturuldu",
  PLATFORM_THEME_UPDATE: "Tema Güncellendi",
  DEV_DEMO_LOAD: "Yerel Demo Verisi Yüklendi",
  DEV_DEMO_LOAD_SKIPPED: "Yerel Demo Verisi Atlandı",
  DEMO_REQUEST_CREATE: "Demo Kurum Oluşturuldu",
  DEMO_PACKAGE_LOAD: "Demo Paketi Yüklendi",
  LIVE_DEMO_DATA_LOAD: "Canlı Demo Verisi Yüklendi",
  SEED: "Başlangıç Verisi Oluşturuldu",
};

const WORD_LABELS: Record<string, string> = {
  SETTINGS: "Ayar",
  UPDATE: "Güncellendi",
  SMS: "SMS",
  TEMPLATE: "Şablon",
  CUSTOM: "Özel",
  SAVE: "Kaydedildi",
  RESET: "Varsayılana Döndürüldü",
  CREATE: "Oluşturuldu",
  CREATED: "Oluşturuldu",
  DELETE: "Silindi",
  DELETED: "Silindi",
  REMOVE: "Kaldırıldı",
  UPDATED: "Güncellendi",
  FAILED: "Başarısız",
  FAIL: "Başarısız",
  CANCEL: "İptal Edildi",
  CANCELLED: "İptal Edildi",
  AUTO: "Otomatik",
  REMINDER: "Hatırlatma",
  PAYMENT: "Tahsilat",
  PAYMENTS: "Tahsilatlar",
  PATIENT: "Hasta",
  FOLLOW: "Takip",
  UP: "",
  EVENT: "Not",
  LAB: "Laboratuvar",
  ORDER: "İş",
  TRIP: "Gönderim",
  INVOICE: "Fatura",
  STOCK: "Stok",
  ITEM: "Kart",
  MOVEMENT: "Hareket",
  FIRMA: "Firma",
  ISLEM: "Cari Hareket",
  KONTAKT: "Yetkili",
  PURCHASE: "Satın Alma",
  PRICE: "Fiyat",
  POS: "POS",
  SUPPORT: "Destek",
  CLINIC: "Klinik",
  TASK: "Görev",
  EXPENSE: "Gider",
  CATEGORY: "Türü",
  GIDER: "Gider",
  KASA: "Kasa",
  TAKSIT: "Taksit",
  PLAN: "Planı",
  PRESCRIPTION: "Reçete",
  TREATMENT: "Tedavi",
  EXAM: "Muayene",
  APPOINTMENT: "Randevu",
  BOOKING: "Randevu",
  REQUEST: "Talebi",
  PUBLIC: "Online",
  WAITLIST: "Bekleme Listesi",
  DOCTOR: "Hekim",
  BLOCK: "Blokaj",
  STAFF: "Personel",
  PASSWORD: "Şifre",
  PROFILE: "Profil",
  TWO: "İki",
  FACTOR: "Aşamalı Doğrulama",
  ENABLE: "Açıldı",
  DISABLE: "Kapatıldı",
  CONSENT: "Onam",
  DOCUMENT: "Belge",
  MESSAGE: "Mesaj",
  ANNOUNCEMENT: "Duyuru",
  PLATFORM: "Platform",
  THEME: "Tema",
  DEMO: "Demo",
  DEV: "Geliştirici",
  DATA: "Veri",
  EXPORT: "Dışa Aktarım",
  IMPORT: "İçe Aktarım",
  PACKAGE: "Paket",
  LOAD: "Yüklendi",
  BILGI: "Bilgilendirme",
  HATIRLATMA: "Hatırlatma",
  ANKET: "Değerlendirme",
  TOPLU: "Toplu Gönderim",
};

export function getAuditActionLabel(action: string, detail?: string | null): string {
  if (action === "SETTINGS_UPDATE" && /sms/i.test(detail || "")) return "SMS Ayarı Güncellendi";
  if (ACTION_LABELS[action]) return ACTION_LABELS[action];

  return action
    .split("_")
    .filter(Boolean)
    .map((part) => WORD_LABELS[part] || part.charAt(0) + part.slice(1).toLocaleLowerCase("tr-TR"))
    .filter(Boolean)
    .join(" ");
}

export function getAuditScopeLabel(action: string, detail?: string | null): string {
  if (action === "LOGIN" || action === "LOGOUT" || action.startsWith("PROFILE_") || action.startsWith("PASSWORD_")) return "Oturum";
  if (action.startsWith("PATIENT_") || action.startsWith("DOCUMENT_") || action.startsWith("CONSENT_")) return "Hasta";
  if (action.startsWith("APPOINTMENT_") || action.startsWith("BOOKING_REQUEST_") || action.startsWith("PUBLIC_BOOKING_") || action.startsWith("WAITLIST_") || action.startsWith("DOCTOR_BLOCK_")) return "Randevu";
  if (action.startsWith("EXAM_") || action.startsWith("TREATMENT_") || action.startsWith("PRESCRIPTION_")) return "Tedavi";
  if (action.startsWith("PAYMENT_") || action.startsWith("KASA_") || action.startsWith("GIDER_") || action.startsWith("TAKSIT_") || action.startsWith("FIRMA_") || action.startsWith("PURCHASE_") || action.startsWith("EXPENSE_")) return "Finans";
  if (action.startsWith("LAB_")) return "Laboratuvar";
  if (action.startsWith("STOCK_")) return "Stok";
  if (action.startsWith("SMS_") || (action === "SETTINGS_UPDATE" && /sms/i.test(detail || ""))) return "SMS";
  if (action.startsWith("SETTINGS_") || action.startsWith("POS_") || action.startsWith("PRICE_") || action.startsWith("SMS_TEMPLATE_") || action.startsWith("FOLLOW_UP_TYPES_")) return "Ayarlar";
  if (action.startsWith("CLINIC_TASK_") || action.startsWith("REMINDER_")) return "Görev";
  if (action.startsWith("SUPPORT_")) return "Destek";
  if (action.startsWith("MESSAGE_") || action.startsWith("ANNOUNCEMENT_")) return "İletişim";
  if (action.startsWith("DEV_") || action.startsWith("DEMO_")) return "Sistem";
  return "Genel";
}
