export const COUNTRY_CODES = [
  { code: "+90", iso: "tr", name: "Türkiye", label: "Türkiye +90" },
  { code: "+93", iso: "af", name: "Afganistan", label: "Afganistan +93" },
  { code: "+355", iso: "al", name: "Arnavutluk", label: "Arnavutluk +355" },
  { code: "+213", iso: "dz", name: "Cezayir", label: "Cezayir +213" },
  { code: "+376", iso: "ad", name: "Andorra", label: "Andorra +376" },
  { code: "+49", iso: "de", name: "Almanya", label: "Almanya +49" },
  { code: "+1", iso: "us", name: "ABD / Kanada", label: "ABD / Kanada +1" },
  { code: "+971", iso: "ae", name: "Birleşik Arap Emirlikleri", label: "Birleşik Arap Emirlikleri +971" },
  { code: "+44", iso: "gb", name: "Birleşik Krallık", label: "Birleşik Krallık +44" },
  { code: "+31", iso: "nl", name: "Hollanda", label: "Hollanda +31" },
  { code: "+33", iso: "fr", name: "Fransa", label: "Fransa +33" },
  { code: "+39", iso: "it", name: "İtalya", label: "İtalya +39" },
  { code: "+34", iso: "es", name: "İspanya", label: "İspanya +34" },
  { code: "+32", iso: "be", name: "Belçika", label: "Belçika +32" },
  { code: "+41", iso: "ch", name: "İsviçre", label: "İsviçre +41" },
  { code: "+46", iso: "se", name: "İsveç", label: "İsveç +46" },
  { code: "+47", iso: "no", name: "Norveç", label: "Norveç +47" },
  { code: "+45", iso: "dk", name: "Danimarka", label: "Danimarka +45" },
  { code: "+7", iso: "ru", name: "Rusya", label: "Rusya +7" },
  { code: "+380", iso: "ua", name: "Ukrayna", label: "Ukrayna +380" },
  { code: "+995", iso: "ge", name: "Gürcistan", label: "Gürcistan +995" },
  { code: "+994", iso: "az", name: "Azerbaycan", label: "Azerbaycan +994" },
  { code: "+98", iso: "ir", name: "İran", label: "İran +98" },
  { code: "+964", iso: "iq", name: "Irak", label: "Irak +964" },
  { code: "+966", iso: "sa", name: "Suudi Arabistan", label: "Suudi Arabistan +966" },
  { code: "+61", iso: "au", name: "Avustralya", label: "Avustralya +61" },
];
