export type CatalogPriceItem = {
  id: string;
  code: string;
  treatment: string;
  amount: number;
};

export const ACTIVE_PRICE_LIST_STORAGE_KEY = "klinikmodern-active-price-list";

export const TDB_ACTIVE_CATALOG_YEAR = 2026;

export function tdbOfficialTariffPdfUrl(year: number) {
  return `https://www.tdb.org.tr/tdb/v2/ekler/${year}_Yili_Rehber_Tarife_Kitapcigi.pdf`;
}

export async function detectLatestPublishedTdbTariffYear(maxYear = new Date().getFullYear() + 1) {
  for (let year = Math.max(maxYear, TDB_ACTIVE_CATALOG_YEAR); year > TDB_ACTIVE_CATALOG_YEAR; year -= 1) {
    try {
      const response = await fetch(tdbOfficialTariffPdfUrl(year), { method: "HEAD", cache: "no-store" });
      if (response.ok) return year;
    } catch {}
  }
  return TDB_ACTIVE_CATALOG_YEAR;
}

export const TDB_2026_CORE_PRICE_CATALOG: CatalogPriceItem[] = [
  { id: "tdb-1-1", code: "1-1", treatment: "Dişhekimi Muayenesi", amount: 1650 },
  { id: "tdb-1-2", code: "1-2", treatment: "Uzman Dişhekimi Muayenesi", amount: 2035 },
  { id: "tdb-1-3", code: "1-3", treatment: "Kontrol Hekim Muayenesi", amount: 1430 },
  { id: "tdb-1-4", code: "1-4", treatment: "Konsültasyon", amount: 1110 },
  { id: "tdb-1-5", code: "1-5", treatment: "Uzman Dişhekimi Konsültasyonu", amount: 1445 },
  { id: "tdb-1-6", code: "1-6", treatment: "Hipnoz (Seans Başına)", amount: 3355 },
  { id: "tdb-1-7", code: "1-7", treatment: "Akupunktur Uygulama (Seans Başına)", amount: 2750 },
  { id: "tdb-1-8", code: "1-8", treatment: "Teşhis ve Tedavi Planlaması", amount: 1535 },
  { id: "tdb-1-9", code: "1-9", treatment: "Oral Hijyen Eğitimi", amount: 1175 },
  { id: "tdb-1-10", code: "1-10", treatment: "Tükürük Akış Hızı ve Tamponlama Kapasitesi Tayini", amount: 1670 },
  { id: "tdb-1-11", code: "1-11", treatment: "Tükürükte Mikrobiyolojik Analiz", amount: 2805 },
  { id: "tdb-1-12", code: "1-12", treatment: "Gnatoloji, T.M.E. Kas Muayenesi (Oklüzyon Kontrolü)", amount: 5280 },
  { id: "tdb-1-13", code: "1-13", treatment: "Vitalite Kontrolu (Diş Başına)", amount: 235 },
  { id: "tdb-1-14", code: "1-14", treatment: "Diş Röntgen Filmi (Periapikal)", amount: 830 },
  { id: "tdb-1-15", code: "1-15", treatment: "Oklüzal Film", amount: 865 },
  { id: "tdb-1-16", code: "1-16", treatment: "Bite - Wing Radyografi", amount: 830 },
  { id: "tdb-1-17", code: "1-17", treatment: "Ekstra Oral Röntgen Filmi", amount: 955 },
  { id: "tdb-1-18", code: "1-18", treatment: "Panaromik Film", amount: 2040 },
  { id: "tdb-1-19", code: "1-19", treatment: "Lateral Sefalometrik Film", amount: 2050 },
  { id: "tdb-1-20", code: "1-20", treatment: "Antero-Posterior Sefalometrik Film", amount: 2030 },
  { id: "tdb-1-21", code: "1-21", treatment: "İntra Oral Dijital Radyografi (RVG veya Fosfor Plak)", amount: 990 },
  { id: "tdb-1-22", code: "1-22", treatment: "El Bilek Filmi", amount: 2030 },
  { id: "tdb-1-23", code: "1-23", treatment: "Siyalografi", amount: 2310 },
  { id: "tdb-1-24", code: "1-24", treatment: "Tomografi (Bölgesel)", amount: 2750 },
  { id: "tdb-1-25", code: "1-25", treatment: "Tomografi (Tek Çene)", amount: 4400 },
  { id: "tdb-1-26", code: "1-26", treatment: "Tomografi (İki Çene Çene)", amount: 5940 },
  { id: "tdb-1-27", code: "1-27", treatment: "Eklem Tomografisi (Çift Taraflı)", amount: 6660 },
  { id: "tdb-1-28", code: "1-28", treatment: "Bilgisayarlı Büyük T.M.E. Fonksiyon Testi", amount: 13200 },
  { id: "tdb-1-29", code: "1-29", treatment: "Bilgisayarlı Kas Tonus Analizi", amount: 5995 },
  { id: "tdb-1-30", code: "1-30", treatment: "T.M.E. Filmi ve Tetkiki", amount: 2670 },
  { id: "tdb-1-31", code: "1-31", treatment: "Lokal Anestezi (Enjeksiyon - İnfiltratif)", amount: 370 },
  { id: "tdb-1-32", code: "1-32", treatment: "Lokal Anestezi (Rejyonal)", amount: 370 },
  { id: "tdb-1-33", code: "1-33", treatment: "Raporlama", amount: 2000 },
  { id: "tdb-1-34", code: "1-34", treatment: "Ağız İçi Dijital Tarama", amount: 2750 },
  { id: "tdb-2-1", code: "2-1", treatment: "Amalgam Dolgu (Bir Yüzlü)", amount: 2845 },
  { id: "tdb-2-2", code: "2-2", treatment: "Amalgam Dolgu (İki Yüzlü)", amount: 3805 },
  { id: "tdb-2-3", code: "2-3", treatment: "Amalgam Dolgu (Üç Yüzlü)", amount: 4845 },
  { id: "tdb-2-4", code: "2-4", treatment: "Kompozit Dolgu (Bir Yüzlü)", amount: 3375 },
  { id: "tdb-2-5", code: "2-5", treatment: "Kompozit Dolgu (İki Yüzlü)", amount: 4235 },
  { id: "tdb-2-6", code: "2-6", treatment: "Kompozit Dolgu (Üç Yüzlü)", amount: 5300 },
  { id: "tdb-2-7", code: "2-7", treatment: "Direkt Kompozit Laminate Restorasyonu", amount: 9295 },
  { id: "tdb-2-8", code: "2-8", treatment: "Black V Kole Dolgusu (Kompozit)", amount: 2720 },
  { id: "tdb-2-9", code: "2-9", treatment: "Cam İonomer Dolgu", amount: 2675 },
  { id: "tdb-2-10", code: "2-10", treatment: "Black V Kole Dolgusu (Cam İonomer)", amount: 2115 },
  { id: "tdb-2-11", code: "2-11", treatment: "İnley Dolgu * (Bir Yüzlü)", amount: 6285 },
  { id: "tdb-2-12", code: "2-12", treatment: "İnley Dolgu * (İki Yüzlü)", amount: 6490 },
  { id: "tdb-2-13", code: "2-13", treatment: "İnley Dolgu * (Üç Yüzlü)", amount: 6770 },
  { id: "tdb-2-14", code: "2-14", treatment: "Kompozit İnley Dolgu (Bir Yüzlü)", amount: 6050 },
  { id: "tdb-2-15", code: "2-15", treatment: "Kompozit İnley Dolgu (İki Yüzlü)", amount: 6050 },
  { id: "tdb-2-16", code: "2-16", treatment: "Kompozit İnley Dolgu (Üç Yüzlü)", amount: 6050 },
  { id: "tdb-2-17", code: "2-17", treatment: "Seramik İnley Dolgu (Bir Yüzlü)", amount: 15620 },
  { id: "tdb-2-18", code: "2-18", treatment: "Seramik İnley Dolgu (İki Yüzlü)", amount: 15620 },
  { id: "tdb-2-19", code: "2-19", treatment: "Seramik İnley Dolgu (Üç Yüzlü)", amount: 15620 },
  { id: "tdb-2-20", code: "2-20", treatment: "Onley *", amount: 7780 },
  { id: "tdb-2-21", code: "2-21", treatment: "Onley * (Seramik)", amount: 15620 },
  { id: "tdb-2-22", code: "2-22", treatment: "Pinley *", amount: 7865 },
  { id: "tdb-2-23", code: "2-23", treatment: "Dolgu (Restorasyon) Tamiri", amount: 2920 },
  { id: "tdb-2-24", code: "2-24", treatment: "Dolgu Sökümü (Tek Diş)", amount: 1480 },
  { id: "tdb-2-25", code: "2-25", treatment: "Kuafaj (Dolgu Hariç)", amount: 440 },
  { id: "tdb-2-26", code: "2-26", treatment: "Ekstirpasyon (Her Kanal İçin)", amount: 2010 },
  { id: "tdb-2-27", code: "2-27", treatment: "Kanal Tedavisi - Tek Kanal (Dolgu Hariç)", amount: 4610 },
  { id: "tdb-2-28", code: "2-28", treatment: "Kanal Tedavisi - İki Kanal (Dolgu Hariç)", amount: 7220 },
  { id: "tdb-2-29", code: "2-29", treatment: "Kanal Tedavisi - Üç Kanal (Dolgu Hariç)", amount: 10350 },
  { id: "tdb-2-30", code: "2-30", treatment: "Kanal Tedavisi - İlave Her Kanal İçin", amount: 2500 },
  { id: "tdb-2-31", code: "2-31", treatment: "Periapikal Lezyonlu Dişte Kanal Tedavisi - Tek Kanal (Dolgu Hariç)", amount: 5055 },
  { id: "tdb-2-32", code: "2-32", treatment: "Periapikal Lezyonlu Dişte Kanal Tedavisi - İki Kanal (Dolgu Hariç)", amount: 7700 },
  { id: "tdb-2-33", code: "2-33", treatment: "Periapikal Lezyonlu Dişte Kanal Tedavisi - Üç Kanal (Dolgu Hariç)", amount: 10980 },
  { id: "tdb-2-34", code: "2-34", treatment: "Kanal Dolgusu Sökümü (Her Kanal İçin)", amount: 1740 },
  { id: "tdb-2-35", code: "2-35", treatment: "Kanal Dolgusu Tekrarı (Retreatment - Her Kanal İçin - Dolgu Hariç)", amount: 4510 },
  { id: "tdb-2-36", code: "2-36", treatment: "Kanal Pansumanı (Seans Başı)", amount: 1205 },
  { id: "tdb-2-37", code: "2-37", treatment: "Kanal İçi Hazır Post Uygulaması (Metal) (Dolgu Ücreti Hariç)", amount: 3075 },
  { id: "tdb-2-38", code: "2-38", treatment: "Kanal İçi Fiber Post Uygulaması (Dolgu Ücreti Hariç)", amount: 4950 },
  { id: "tdb-2-39", code: "2-39", treatment: "Kanaldan Kırılmış Materyal Çıkartılması", amount: 6875 },
  { id: "tdb-2-40", code: "2-40", treatment: "Kanalda Perforasyon Tamiri (MTA vb.)", amount: 3280 },
  { id: "tdb-2-41", code: "2-41", treatment: "Dentin Pini Uygulaması (Her Pin Başına)", amount: 555 },
  { id: "tdb-2-42", code: "2-42", treatment: "Endokron", amount: 13750 },
  { id: "tdb-2-43", code: "2-43", treatment: "Hassasiyet Tedavisi (Tek Diş)", amount: 1220 },
  { id: "tdb-2-44", code: "2-44", treatment: "Hassasiyet Tedavisi (Tam Çene)", amount: 3520 },
  { id: "tdb-2-45", code: "2-45", treatment: "Diş Ağartma (Beyazlatma Vital Tek Diş En Çok 4 Adet) (Malzeme Ücreti Hariç)", amount: 2145 },
  { id: "tdb-2-46", code: "2-46", treatment: "Diş Ağartma (Beyazlatma - Devital Tek Diş ) (Seans Başına - Dolgu Hariç)", amount: 2475 },
  { id: "tdb-2-47", code: "2-47", treatment: "Diş Ağartma (Beyazlatma - Tek Çene) (Malzeme Ücreti Hariç)", amount: 11935 },
  { id: "tdb-2-48", code: "2-48", treatment: "Rubber-Dam Uygulaması", amount: 1155 },
  { id: "tdb-3-1", code: "3-1", treatment: "Aşındırma ile Sürme Rehberliği (Seans Başına)", amount: 1640 },
  { id: "tdb-3-2", code: "3-2", treatment: "Fissür Örtülmesi (Sealant - Tek Diş)", amount: 1445 },
  { id: "tdb-3-3", code: "3-3", treatment: "Yüzeysel Flor Uygulaması (Yarım Çene)", amount: 1375 },
  { id: "tdb-3-4", code: "3-4", treatment: "Kompomer Dolgu", amount: 4180 },
  { id: "tdb-3-5", code: "3-5", treatment: "Rezin İnfilitrasyonu Tedavisi", amount: 7150 },
  { id: "tdb-3-6", code: "3-6", treatment: "Amputasyon (Dolgu-Kron Üst Yapı-Biyomateryal Hariç)", amount: 3850 },
  { id: "tdb-3-7", code: "3-7", treatment: "Süt Dişi Kanal Tedavisi", amount: 6765 },
  { id: "tdb-3-8", code: "3-8", treatment: "Açık Apeksli Dişte Kanal Tedavisi (Her Kanal İçin - Dolgu Hariç) (Pansuman Ücretleri Hariç)", amount: 12780 },
  { id: "tdb-3-9", code: "3-9", treatment: "Açık Apeksli Dişte Apikal Bariyer (Her Kanal İçin - Dolgu ve Pansuman Ücretleri Hariç)", amount: 5830 },
  { id: "tdb-3-10", code: "3-10", treatment: "Yer Tutucu (Sabit)", amount: 7480 },
  { id: "tdb-3-11", code: "3-11", treatment: "Yer Tutucu (Hareketli)", amount: 10010 },
  { id: "tdb-3-12", code: "3-12", treatment: "Prefabrike Kron *", amount: 3810 },
  { id: "tdb-3-13", code: "3-13", treatment: "Strip Kron", amount: 3575 },
  { id: "tdb-3-14", code: "3-14", treatment: "Travma Splinti", amount: 8195 },
  { id: "tdb-3-15", code: "3-15", treatment: "Çocuk Protezi", amount: 9350 },
  { id: "tdb-3-16", code: "3-16", treatment: "Çocuk Protezi (Akrilik - Bölümlü - Tek Çene)", amount: 15050 },
  { id: "tdb-3-17", code: "3-17", treatment: "Çocuk Protezi (Akrilik - Tam - Tek Çene)", amount: 16995 },
  { id: "tdb-3-18", code: "3-18", treatment: "Avülsiyon Tedavisi", amount: 18700 },
  { id: "tdb-4-1", code: "4-1", treatment: "Tam Protez (Akrilik - Tek Çene)", amount: 31900 },
  { id: "tdb-4-2", code: "4-2", treatment: "Bölümlü Protez (Akrilik - Tek Çene)", amount: 30690 },
  { id: "tdb-4-3", code: "4-3", treatment: "Tam Protez (Döküm Metal ile Güçlendirilmiş - Tek Çene)", amount: 39600 },
  { id: "tdb-4-4", code: "4-4", treatment: "Bölümlü Protez (Döküm Metal ile Güçlendirilmiş - Tek Çene)", amount: 38500 },
  { id: "tdb-4-5", code: "4-5", treatment: "Hassas Tutuculu Protezler (Hassas Tutucu Ücreti Hariç - Tek Çene)", amount: 40150 },
  { id: "tdb-4-6", code: "4-6", treatment: "İmplant Destekli Hareketli Protezler (Hassas Tutucu Ücreti Hariç - Tek Çene)", amount: 40700 },
  { id: "tdb-4-7", code: "4-7", treatment: "Geçici (İmmediat) Protez (Akrilik - Tek Çene)", amount: 22285 },
  { id: "tdb-4-8", code: "4-8", treatment: "Besleme (Tek Çene)", amount: 11965 },
  { id: "tdb-4-9", code: "4-9", treatment: "Kaide Yenileme (Rebazaj - Tek Çene)", amount: 12430 },
  { id: "tdb-4-10", code: "4-10", treatment: "Proteze Yumuşak Akrilik Uygulaması (Geçici Tek Çene)", amount: 8070 },
  { id: "tdb-4-11", code: "4-11", treatment: "Proteze Yumuşak Akrilik Uygulaması (Daimi Tek Çene)", amount: 12610 },
  { id: "tdb-4-12", code: "4-12", treatment: "Tamir (Akrilik Protezler, Kırık veya Çatlak)", amount: 3805 },
  { id: "tdb-4-13", code: "4-13", treatment: "Kroşe İlavesi", amount: 4290 },
  { id: "tdb-4-14", code: "4-14", treatment: "Metal İskelet Tamiri", amount: 4180 },
  { id: "tdb-4-15", code: "4-15", treatment: "Diş İlavesi (Tek Diş)", amount: 4180 },
  { id: "tdb-4-16", code: "4-16", treatment: "Roach Köprü", amount: 7645 },
  { id: "tdb-4-17", code: "4-17", treatment: "Gece Plağı (Yumuşak)", amount: 5885 },
  { id: "tdb-4-18", code: "4-18", treatment: "Gece Plağı (Sert Oklüzal Splintleme)", amount: 20240 },
  { id: "tdb-4-19", code: "4-19", treatment: "Pinley ve Çeşitleri *", amount: 8740 },
  { id: "tdb-4-20", code: "4-20", treatment: "Tek Parça Döküm Kuron", amount: 7735 },
  { id: "tdb-4-21", code: "4-21", treatment: "Veneer Kuron (Akrilik)", amount: 11220 },
  { id: "tdb-4-22", code: "4-22", treatment: "Veneer Kuron ** (Seramik)", amount: 12100 },
  { id: "tdb-4-23", code: "4-23", treatment: "İmplant Üstü Veneer Kuron (Seramik) (Abutment Ücreti Hariç)", amount: 13680 },
  { id: "tdb-4-24", code: "4-24", treatment: "Laminate Veneer Kompozit", amount: 9295 },
  { id: "tdb-4-25", code: "4-25", treatment: "Laminate Veneer (Akrilik)", amount: 10785 },
  { id: "tdb-4-26", code: "4-26", treatment: "Laminate Veneer (Seramik)", amount: 26400 },
  { id: "tdb-4-27", code: "4-27", treatment: "Jaket Kuron (Akrilik)", amount: 7480 },
  { id: "tdb-4-28", code: "4-28", treatment: "Jaket Kuron (Kompozit)", amount: 7205 },
  { id: "tdb-4-29", code: "4-29", treatment: "Tam Seramik Kuron (Metal Desteksiz)", amount: 21450 },
  { id: "tdb-4-30", code: "4-30", treatment: "Teleskop Kuron* (Koping)", amount: 9895 },
  { id: "tdb-4-31", code: "4-31", treatment: "Kuronlarda Freze Tekniği Farkı", amount: 1595 },
  { id: "tdb-4-32", code: "4-32", treatment: "Döküm Post Core (Pivo) (Üst Yapı Hariç)", amount: 6860 },
  { id: "tdb-4-33", code: "4-33", treatment: "Adeziv Köprü (Maryland vb. gibi)", amount: 11550 },
  { id: "tdb-4-34", code: "4-34", treatment: "Geçici Kuron (Tek Diş İçin)", amount: 2245 },
  { id: "tdb-4-35", code: "4-35", treatment: "Kuron Sökümü (Tek Sabit Üye İçin)", amount: 1875 },
  { id: "tdb-4-36", code: "4-36", treatment: "Düşmüş Kuron ve Köprü Simantasyonu (Her Sabit Üye İçin)", amount: 1225 },
  { id: "tdb-4-37", code: "4-37", treatment: "Kuron Köprü Tamiri * (Her Üye İçin)", amount: 5005 },
  { id: "tdb-4-38", code: "4-38", treatment: "Diş Üstü Protezi (Overdenture - Tek Çene) (**)", amount: 26055 },
  { id: "tdb-4-39", code: "4-39", treatment: "Damak Yarığı Protezi (Velum Uzantılı Aparey) (**)", amount: 26185 },
  { id: "tdb-4-40", code: "4-40", treatment: "Yeni Doğanda Preoperatif Aparey (Vida Ücreti Ayrıca Alınır) (**)", amount: 22030 },
  { id: "tdb-4-41", code: "4-41", treatment: "Geçici Obturatörler (**)", amount: 19235 },
  { id: "tdb-4-42", code: "4-42", treatment: "Basit Çene Defektlerinde Protetik Tedavi (**)", amount: 35210 },
  { id: "tdb-4-43", code: "4-43", treatment: "Komplike Çene Defektlerinde Protetik Tedavi (**)", amount: 42275 },
  { id: "tdb-4-44", code: "4-44", treatment: "Yüz Protezleri (Yumuşak Akrilik İle)", amount: 68750 },
  { id: "tdb-4-45", code: "4-45", treatment: "Göz Protezi (Oküler)", amount: 72695 },
  { id: "tdb-4-46", code: "4-46", treatment: "Oklüzal Aşındırmalar", amount: 6820 },
  { id: "tdb-4-47", code: "4-47", treatment: "Oklüzyon Düzeltilmesi", amount: 10150 },
  { id: "tdb-4-48", code: "4-48", treatment: "T.M.E. Stabilizasyon Splinti", amount: 19800 },
  { id: "tdb-4-49", code: "4-49", treatment: "İmplant Rehberi (Yarım Çene)", amount: 9735 },
  { id: "tdb-4-50", code: "4-50", treatment: "İmplant Rehberi (Tam Çene)", amount: 14300 },
  { id: "tdb-4-51", code: "4-51", treatment: "Zirkonyum Kron", amount: 13750 },
  { id: "tdb-5-1", code: "5-1", treatment: "Diş Çekimi", amount: 2475 },
  { id: "tdb-5-2", code: "5-2", treatment: "Komplikasyonlu Diş Çekimi", amount: 4950 },
  { id: "tdb-5-3", code: "5-3", treatment: "Gömülü Diş Operasyonu", amount: 7975 },
  { id: "tdb-5-4", code: "5-4", treatment: "Gömülü Diş Operasyonu (Kemik Retansiyonlu)", amount: 11715 },
  { id: "tdb-5-5", code: "5-5", treatment: "Tek Kökte Kök Ucu Rezeksiyonu (Kanal Tedavisi ve Dolgu Hariç)", amount: 10450 },
  { id: "tdb-5-6", code: "5-6", treatment: "İki Kökte Kök Ucu Rezeksiyonu (Kanal Tedavisi ve Dolgu Hariç)", amount: 12925 },
  { id: "tdb-5-7", code: "5-7", treatment: "Üç Kökte Kök Ucu Rezeksiyonu (Kanal Tedavisi ve Dolgu Hariç)", amount: 15125 },
  { id: "tdb-5-8", code: "5-8", treatment: "Alveolit Cerrahi Tedavisi", amount: 7455 },
  { id: "tdb-5-9", code: "5-9", treatment: "Kanama Müdahalesi (Basit)", amount: 2560 },
  { id: "tdb-5-10", code: "5-10", treatment: "Kanama Müdahalesi (Dikişli)", amount: 4755 },
  { id: "tdb-5-11", code: "5-11", treatment: "Alveol Plastiği (Yarım Çene)", amount: 10395 },
  { id: "tdb-5-12", code: "5-12", treatment: "Alveol Düzeltilmesi (Yarım Çene)", amount: 10395 },
  { id: "tdb-5-13", code: "5-13", treatment: "Kist Operasyonu (Küçük)", amount: 11055 },
  { id: "tdb-5-14", code: "5-14", treatment: "Kist Operasyonu (1 Cm Büyük)", amount: 16500 },
  { id: "tdb-5-15", code: "5-15", treatment: "Epulis Operasyonu", amount: 7150 },
  { id: "tdb-5-16", code: "5-16", treatment: "Osteomyelitis veya Osteitis Operasyonu (Tek Çene Basit)", amount: 19250 },
  { id: "tdb-5-17", code: "5-17", treatment: "Çene Lüksasyonu", amount: 3795 },
  { id: "tdb-5-18", code: "5-18", treatment: "Vestibüloplasti (Yarım Çene)", amount: 20900 },
  { id: "tdb-5-19", code: "5-19", treatment: "Sinüs Plastiği", amount: 12650 },
  { id: "tdb-5-20", code: "5-20", treatment: "Sert Doku Greftleme (Greft Ücreti Hariç)", amount: 15950 },
  { id: "tdb-5-21", code: "5-21", treatment: "Yumuşak Doku Greftleme (Greft Ücreti Hariç)", amount: 13200 },
  { id: "tdb-5-22", code: "5-22", treatment: "Sinüs Lifting (Biomateryal Ücreti Hariç)", amount: 14465 },
  { id: "tdb-5-23", code: "5-23", treatment: "Biyopsi", amount: 6380 },
  { id: "tdb-5-24", code: "5-24", treatment: "Fibrom Operasyonu", amount: 6645 },
  { id: "tdb-5-25", code: "5-25", treatment: "Apse Drenajı ve Tedavisi (Extraoral)", amount: 11165 },
  { id: "tdb-5-26", code: "5-26", treatment: "Apse Drenajı ve Tedavisi (İntraoral)", amount: 8790 },
  { id: "tdb-5-27", code: "5-27", treatment: "Kapişon İzalesi - İmplant Üstü Açılması", amount: 3640 },
  { id: "tdb-5-28", code: "5-28", treatment: "Stomatit Tedavisi,", amount: 2395 },
  { id: "tdb-5-29", code: "5-29", treatment: "Fizik Tedavi (İnfraruj Seansı)", amount: 2105 },
  { id: "tdb-5-30", code: "5-30", treatment: "Çene Kırığı (Basit)", amount: 22550 },
  { id: "tdb-5-31", code: "5-31", treatment: "Çene Kırığı (Komplike - Materyal Ücreti Hariç)", amount: 63800 },
  { id: "tdb-5-32", code: "5-32", treatment: "Reimplantasyon", amount: 11550 },
  { id: "tdb-5-33", code: "5-33", treatment: "Ototransplantasyon", amount: 17050 },
  { id: "tdb-5-34", code: "5-34", treatment: "Kemik İçi İmplant (Tek Silindirik İmplant Ücreti Hariç)", amount: 22440 },
  { id: "tdb-5-35", code: "5-35", treatment: "Torus Operasyonu (Yarım Çene)", amount: 10780 },
  { id: "tdb-5-36", code: "5-36", treatment: "Odontogenik Tümör Operasyonu (Küçük)", amount: 20350 },
  { id: "tdb-5-37", code: "5-37", treatment: "Odontogenik Tümör Operasyonu (Büyük)", amount: 26950 },
  { id: "tdb-5-38", code: "5-38", treatment: "Nevralji Tedavisi (Alkol Enjeksiyonu)", amount: 3850 },
  { id: "tdb-5-39", code: "5-39", treatment: "Nevralji Tedavisi Cerrahi (Nöroktomi vb.)", amount: 10450 },
  { id: "tdb-5-40", code: "5-40", treatment: "Tükürük Bezi Kanalından Taş Çıkarma (Basit)", amount: 7975 },
  { id: "tdb-5-41", code: "5-41", treatment: "Tükürük Bezi Kanalından Taş Çıkarma (Komplike)", amount: 12650 },
  { id: "tdb-5-42", code: "5-42", treatment: "Ortodontik Tedavi Amaçlı Gömük Dişlerin Üzerinin Açılması", amount: 10450 },
  { id: "tdb-5-43", code: "5-43", treatment: "T.M.E. Mekonoterapi", amount: 3575 },
  { id: "tdb-5-44", code: "5-44", treatment: "T.M.E. İçi Enjeksiyon (Tek Taraflı)", amount: 7150 },
  { id: "tdb-5-45", code: "5-45", treatment: "Artrosentez (Tek Taraflı)", amount: 4915 },
  { id: "tdb-5-46", code: "5-46", treatment: "Açık Eklem Cerrahisi (Tek Taraflı)", amount: 82500 },
  { id: "tdb-5-47", code: "5-47", treatment: "Genioplasti", amount: 82500 },
  { id: "tdb-5-48", code: "5-48", treatment: "Segmental Osteotomi", amount: 88000 },
  { id: "tdb-5-49", code: "5-49", treatment: "Osteotomi (Tek Çene)", amount: 92400 },
  { id: "tdb-5-50", code: "5-50", treatment: "Dişhekimliğinde Botulinum Toksin Uygulaması", amount: 11550 },
  { id: "tdb-5-51", code: "5-51", treatment: "İmplant Çıkartılması", amount: 10450 },
  { id: "tdb-5-52", code: "5-52", treatment: "Ankraj Amaçlı Plak Yerleştirme (Malzeme Ücreti Hariç)", amount: 11220 },
  { id: "tdb-5-53", code: "5-53", treatment: "Ankraj Amaçlı Plak Çıkarma", amount: 6600 },
  { id: "tdb-5-54", code: "5-54", treatment: "Zigoma İmplant (İmplant Ücreti Hariç)", amount: 49500 },
  { id: "tdb-5-55", code: "5-55", treatment: "Koronektomi", amount: 10450 },
  { id: "tdb-6-1", code: "6-1", treatment: "Detartraj (Diş Taşı Temizliği - Tek Çene)", amount: 3300 },
  { id: "tdb-6-2", code: "6-2", treatment: "Subgingival Küretaj (Tek Diş)", amount: 1870 },
  { id: "tdb-6-3", code: "6-3", treatment: "Subgingival İlaç Uygulaması", amount: 330 },
  { id: "tdb-6-4", code: "6-4", treatment: "Gingivoplasti (Tek Diş)", amount: 3135 },
  { id: "tdb-6-5", code: "6-5", treatment: "Gingivektomi (Tek Diş)", amount: 3245 },
  { id: "tdb-6-6", code: "6-6", treatment: "Flap Operasyonu (Subgingival Küretaj Dahil - Tek Diş)", amount: 5225 },
  { id: "tdb-6-7", code: "6-7", treatment: "Tunnel Operasyonu (Tek Diş)", amount: 4445 },
  { id: "tdb-6-8", code: "6-8", treatment: "Hemiseksiyon (Kök Amputasyonu - Kanal Tedavisi Hariç)", amount: 3845 },
  { id: "tdb-6-9", code: "6-9", treatment: "Serbest Diş Eti Grefti (Tek Diş)", amount: 13145 },
  { id: "tdb-6-10", code: "6-10", treatment: "Saplı Yumuşak Doku Grefti (Koronale Kaydırma, Yana Kaydırma,Tek Diş)", amount: 11495 },
  { id: "tdb-6-11", code: "6-11", treatment: "Periodontal Splint (Daimi)", amount: 6370 },
  { id: "tdb-6-12", code: "6-12", treatment: "Periodontal Splint (Geçici)", amount: 8070 },
  { id: "tdb-6-13", code: "6-13", treatment: "Periodontal Şine (Splint - Geçici - Yarım Çene)", amount: 3690 },
  { id: "tdb-6-14", code: "6-14", treatment: "Biyomateryal Uygulaması (Tek Diş - Flap Op. ve Biomateryal Ücreti Hariç)", amount: 1375 },
  { id: "tdb-6-15", code: "6-15", treatment: "Membran Uygulaması (Tek Diş - Flap Op. ve Membran Ücreti Hariç)", amount: 1360 },
  { id: "tdb-6-16", code: "6-16", treatment: "Vestibül Plak (Diş Eti Protezi - Çene Başına)", amount: 9020 },
  { id: "tdb-6-17", code: "6-17", treatment: "Subepitelyal Bağ Dokusu Grefti", amount: 14850 },
  { id: "tdb-6-18", code: "6-18", treatment: "Frenektomi - Frenetomi", amount: 7700 },
  { id: "tdb-6-19", code: "6-19", treatment: "Peri-İmplantitis (Cerrahi) (Biomaterial ve Membran Ücreti Hariç) (Tek İmp.)", amount: 6875 },
  { id: "tdb-6-20", code: "6-20", treatment: "Peri-İmplantitis (Cerrahi Olmayan) (Tek İmp.)", amount: 2965 },
  { id: "tdb-6-21", code: "6-21", treatment: "Papil Oluşturma (Cerrahi) (Tek Papil)", amount: 2910 },
  { id: "tdb-6-22", code: "6-22", treatment: "Papil Oluşturma (Cerrahi Olmayan) (Tek Papil)", amount: 2885 },
  { id: "tdb-6-23", code: "6-23", treatment: "Fiberotomi", amount: 2750 },
  { id: "tdb-7-1", code: "7-1", treatment: "Lateral Sefalometrik Film Analizi", amount: 1675 },
  { id: "tdb-7-2", code: "7-2", treatment: "Antero Posterior Sefalometrik Film Analizi (Frontal Film Analizi)", amount: 1870 },
  { id: "tdb-7-3", code: "7-3", treatment: "Kemik Yaşı Tayini", amount: 645 },
  { id: "tdb-7-4", code: "7-4", treatment: "Ortodontik Fotoğraf", amount: 990 },
  { id: "tdb-7-5", code: "7-5", treatment: "Ortodontik Fotoğraf Tetkiki", amount: 605 },
  { id: "tdb-7-6", code: "7-6", treatment: "Ortodontik Model Yapımı", amount: 1210 },
  { id: "tdb-7-7", code: "7-7", treatment: "Ortodontik Model Analizi", amount: 1480 },
  { id: "tdb-7-8", code: "7-8", treatment: "Ara Dönem Sefalometrik Film Analizi", amount: 990 },
  { id: "tdb-7-9", code: "7-9", treatment: "Ara Dönem Model Yapımı", amount: 1875 },
  { id: "tdb-7-10", code: "7-10", treatment: "Angle Sınıf I Anomalilerinin Ortodontik Tedavisi", amount: 40910 },
  { id: "tdb-7-11", code: "7-11", treatment: "Angle Sınıf II Anomalilerinin Ortodontik Tedavisi", amount: 51395 },
  { id: "tdb-7-12", code: "7-12", treatment: "Angle Sınıf III Anomalilerinin Ortodontik Tedavisi", amount: 62675 },
  { id: "tdb-7-13", code: "7-13", treatment: "Sabit Kapanış Yükseltici Tatbiki (Kısa Süreli)", amount: 3410 },
  { id: "tdb-7-14", code: "7-14", treatment: "Lingual Teknikle Angle Sınıf I Anomalilerinin Ortodontik Tedavisi", amount: 41965 },
  { id: "tdb-7-15", code: "7-15", treatment: "Lingual Teknikle Angle Sınıf II Anomalilerinin Ortodontik Tedavisi", amount: 48400 },
  { id: "tdb-7-16", code: "7-16", treatment: "Lingual Teknikle Angle Sınıf III Anomalilerinin Ortodontik Tedavisi", amount: 57200 },
  { id: "tdb-7-17", code: "7-17", treatment: "Açık Kapanışın Ortodontik Tedavisi", amount: 61030 },
  { id: "tdb-7-18", code: "7-18", treatment: "Önleyici Ortodontik Tedavi", amount: 26125 },
  { id: "tdb-7-19", code: "7-19", treatment: "Kısa Süreli Ortodontik Tedavi", amount: 23290 },
  { id: "tdb-7-20", code: "7-20", treatment: "Pekiştirme Tedavisi", amount: 9295 },
  { id: "tdb-7-21", code: "7-21", treatment: "Pekiştirme Aygıtı (Hawley Aygıtı vb.)", amount: 6765 },
  { id: "tdb-7-22", code: "7-22", treatment: "Sabit Pekiştirme Aygıtı (Lingual Retainer)", amount: 9625 },
  { id: "tdb-7-23", code: "7-23", treatment: "Dudak Yastıkçığı (Lip Bumper)", amount: 10725 },
  { id: "tdb-7-24", code: "7-24", treatment: "Tek Çeneyi İlgilendiren Aparey Yapımı (Vida Hariç)", amount: 7535 },
  { id: "tdb-7-25", code: "7-25", treatment: "Çift Çeneyi İlgilendiren Aparey Yapımı (Frankel Aygıtları - Aktivatör - Bionatör)", amount: 12265 },
  { id: "tdb-7-26", code: "7-26", treatment: "Vida Uygulaması (Tek Vida)", amount: 1965 },
  { id: "tdb-7-27", code: "7-27", treatment: "Sabit Fonksiyonel Aygıt Uygulaması (Jasper - Jumper - Herbest Aygıtı)", amount: 20900 },
  { id: "tdb-7-28", code: "7-28", treatment: "Kayıp Apareyin Yeniden Yapımı (Tek Çene)", amount: 6435 },
  { id: "tdb-7-29", code: "7-29", treatment: "Aparey Tamiri", amount: 3025 },
  { id: "tdb-7-30", code: "7-30", treatment: "Ağız Dışı Aparey Tatbiki (Headgear - Chincap)", amount: 6875 },
  { id: "tdb-7-31", code: "7-31", treatment: "Reverse Headgear", amount: 19635 },
  { id: "tdb-7-32", code: "7-32", treatment: "Düz Ark Teli Tatbiki (Tek Çene NİTİ Telleri)", amount: 2255 },
  { id: "tdb-7-33", code: "7-33", treatment: "Büküm İçeren Tel Tatbiki (Tek Çene)", amount: 2475 },
  { id: "tdb-7-34", code: "7-34", treatment: "Segmental Ark veya Tork Arkı Tatbiki", amount: 2090 },
  { id: "tdb-7-35", code: "7-35", treatment: "Bant Tatbiki (Tek Diş)", amount: 2255 },
  { id: "tdb-7-36", code: "7-36", treatment: "Braket Tatbiki (Tek Diş)", amount: 1925 },
  { id: "tdb-7-37", code: "7-37", treatment: "Lingual Braket Tatbiki (Tek Diş)", amount: 1925 },
  { id: "tdb-7-38", code: "7-38", treatment: "Düşen Bant Tatbiki (Tek Diş)", amount: 2255 },
  { id: "tdb-7-39", code: "7-39", treatment: "Düşen Braket Tatbiki (Tek Diş)", amount: 1925 },
  { id: "tdb-7-40", code: "7-40", treatment: "Bant veya Braket Çıkarılması (Tek Diş)", amount: 785 },
  { id: "tdb-7-41", code: "7-41", treatment: "Lingual Ataçman Tatbiki", amount: 2090 },
  { id: "tdb-7-42", code: "7-42", treatment: "Lingual Ark", amount: 7425 },
  { id: "tdb-7-43", code: "7-43", treatment: "Nance Apareyi", amount: 11275 },
  { id: "tdb-7-44", code: "7-44", treatment: "Hızlı Maksiller Genişletme Apareyi", amount: 13750 },
  { id: "tdb-7-45", code: "7-45", treatment: "Preoperatif Dudak Damak Yarığı (Ortodontik Tedavi)", amount: 33550 },
  { id: "tdb-7-46", code: "7-46", treatment: "Postoperatif Dudak Damak Yarığı (Ortodontik Tedavi)", amount: 14025 },
  { id: "tdb-7-47", code: "7-47", treatment: "T.M.E. Splint Yapımı", amount: 13695 },
  { id: "tdb-7-48", code: "7-48", treatment: "Model Set-Up", amount: 6435 },
  { id: "tdb-7-49", code: "7-49", treatment: "Positioner Yapımı", amount: 15125 },
  { id: "tdb-7-50", code: "7-50", treatment: "Sefalometrik Cerrahi Planı", amount: 3355 },
  { id: "tdb-7-51", code: "7-51", treatment: "Ortodontik Modellerin Face - Bow ile Artikülatöre Taşınması", amount: 7150 },
  { id: "tdb-7-52", code: "7-52", treatment: "Model Cerrahisi", amount: 4070 },
  { id: "tdb-7-53", code: "7-53", treatment: "Oklüzal Cerrahi Splint (Tek Çene)", amount: 12150 },
  { id: "tdb-7-54", code: "7-54", treatment: "Ortodontik Ameliyat Arkı (Tek Çene)", amount: 21080 },
  { id: "tdb-7-55", code: "7-55", treatment: "Sürme Rehberliği", amount: 17765 },
  { id: "tdb-7-56", code: "7-56", treatment: "Ağız İçi Distalizasyon Apareyi (Pendex vb.)", amount: 15895 },
  { id: "tdb-7-57", code: "7-57", treatment: "Gömülü Dişin Diş Dizisinde Yerine Yerleştirilmesi (Tek Diş)", amount: 21065 },
  { id: "tdb-7-58", code: "7-58", treatment: "Reserve Curve'li Niti Ark Tatbiki", amount: 3575 },
  { id: "tdb-7-59", code: "7-59", treatment: "Ortognatik Cerrahi Ortodontik Tedavisi", amount: 69480 },
  { id: "tdb-7-60", code: "7-60", treatment: "Mini Vida Uygulaması", amount: 4950 },
  { id: "tdb-7-61", code: "7-61", treatment: "İnterproksimal Aşındırma (Tek Diş)", amount: 1265 },
  { id: "tdb-7-62", code: "7-62", treatment: "Şeffaf Plaklar ile Ortodontik Tedavi (Hafif) (Plak Ücreti Hariç)", amount: 53900 },
  { id: "tdb-7-63", code: "7-63", treatment: "Şeffaf Plaklar ile Ortodontik Tedavi (Orta) (Plak Ücreti Hariç)", amount: 69300 },
  { id: "tdb-7-64", code: "7-64", treatment: "Şeffaf Plaklar ile Ortodontik Tedavi (Ağır) (Plak Ücreti Hariç)", amount: 95700 },
  { id: "tdb-7-65", code: "7-65", treatment: "Ağız İçi Koruyucu Aparey", amount: 11000 },
];

export const CUSTOM_DENTAL_TREATMENT_TEMPLATES: CatalogPriceItem[] = [
  { id: "ozl-muayene", code: "OZL-001", treatment: "Muayene", amount: 1650 },
  { id: "ozl-kontrol", code: "OZL-002", treatment: "Kontrol", amount: 1430 },
  { id: "ozl-konsultasyon", code: "OZL-003", treatment: "Konsültasyon", amount: 1110 },
  { id: "ozl-planlama", code: "OZL-004", treatment: "Teşhis ve Tedavi Planlaması", amount: 1535 },
  { id: "ozl-rontgen", code: "OZL-005", treatment: "Periapikal Röntgen", amount: 830 },
  { id: "ozl-panoramik", code: "OZL-006", treatment: "Panoramik Film", amount: 2040 },
  { id: "ozl-dolgu-1", code: "OZL-007", treatment: "Kompozit Dolgu (Bir Yüzlü)", amount: 3375 },
  { id: "ozl-dolgu-2", code: "OZL-008", treatment: "Kompozit Dolgu (İki Yüzlü)", amount: 4235 },
  { id: "ozl-dolgu-3", code: "OZL-009", treatment: "Kompozit Dolgu (Üç Yüzlü)", amount: 5300 },
  { id: "ozl-laminate-kompozit", code: "OZL-010", treatment: "Direkt Kompozit Laminate Restorasyonu", amount: 9295 },
  { id: "ozl-kole-kompozit", code: "OZL-011", treatment: "Black V Kole Dolgusu (Kompozit)", amount: 2720 },
  { id: "ozl-cam-ionomer", code: "OZL-012", treatment: "Cam İonomer Dolgu", amount: 2675 },
  { id: "ozl-inley-kompozit", code: "OZL-013", treatment: "Kompozit İnley Dolgu", amount: 6050 },
  { id: "ozl-onley-seramik", code: "OZL-014", treatment: "Onley (Seramik)", amount: 15620 },
  { id: "ozl-kanal-1", code: "OZL-015", treatment: "Kanal Tedavisi (Tek Kanal)", amount: 4610 },
  { id: "ozl-kanal-2", code: "OZL-016", treatment: "Kanal Tedavisi (İki Kanal)", amount: 7220 },
  { id: "ozl-kanal-3", code: "OZL-017", treatment: "Kanal Tedavisi (Üç Kanal)", amount: 10350 },
  { id: "ozl-lezyon-kanal-1", code: "OZL-018", treatment: "Periapikal Lezyonlu Kanal Tedavisi (Tek Kanal)", amount: 5055 },
  { id: "ozl-lezyon-kanal-2", code: "OZL-019", treatment: "Periapikal Lezyonlu Kanal Tedavisi (İki Kanal)", amount: 7700 },
  { id: "ozl-lezyon-kanal-3", code: "OZL-020", treatment: "Periapikal Lezyonlu Kanal Tedavisi (Üç Kanal)", amount: 10980 },
  { id: "ozl-retreatment", code: "OZL-021", treatment: "Kanal Retreatment (Her Kanal)", amount: 4510 },
  { id: "ozl-fiber-post", code: "OZL-022", treatment: "Fiber Post Uygulaması", amount: 4950 },
  { id: "ozl-endokron", code: "OZL-023", treatment: "Endokron", amount: 13750 },
  { id: "ozl-hassasiyet-tek", code: "OZL-024", treatment: "Hassasiyet Tedavisi (Tek Diş)", amount: 1220 },
  { id: "ozl-hassasiyet-cene", code: "OZL-025", treatment: "Hassasiyet Tedavisi (Tam Çene)", amount: 3520 },
  { id: "ozl-beyazlatma-tek", code: "OZL-026", treatment: "Beyazlatma Vital Tek Diş", amount: 2145 },
  { id: "ozl-beyazlatma-cene", code: "OZL-027", treatment: "Beyazlatma Tek Çene", amount: 11935 },
  { id: "ozl-kompomer", code: "OZL-028", treatment: "Kompomer Dolgu", amount: 4180 },
  { id: "ozl-pedokanal", code: "OZL-029", treatment: "Süt Dişi Kanal Tedavisi", amount: 6765 },
  { id: "ozl-prefabrike-kron", code: "OZL-030", treatment: "Prefabrike Kron", amount: 3810 },
  { id: "ozl-strip-kron", code: "OZL-031", treatment: "Strip Kron", amount: 3575 },
  { id: "ozl-yer-tutucu-sabit", code: "OZL-032", treatment: "Yer Tutucu (Sabit)", amount: 7480 },
  { id: "ozl-yer-tutucu-hareketli", code: "OZL-033", treatment: "Yer Tutucu (Hareketli)", amount: 10010 },
  { id: "ozl-gece-plagi-yumusak", code: "OZL-034", treatment: "Gece Plağı (Yumuşak)", amount: 5885 },
  { id: "ozl-gece-plagi-sert", code: "OZL-035", treatment: "Gece Plağı (Sert Oklüzal Splint)", amount: 20240 },
  { id: "ozl-zirkon", code: "OZL-036", treatment: "Zirkonyum Kron", amount: 13750 },
  { id: "ozl-laminate-seramik", code: "OZL-037", treatment: "Laminate Veneer (Seramik)", amount: 26400 },
  { id: "ozl-tam-seramik", code: "OZL-038", treatment: "Tam Seramik Kuron", amount: 21450 },
  { id: "ozl-gecici-kuron", code: "OZL-039", treatment: "Geçici Kuron", amount: 2245 },
  { id: "ozl-cekim", code: "OZL-040", treatment: "Diş Çekimi", amount: 2475 },
  { id: "ozl-cekim-zor", code: "OZL-041", treatment: "Komplikasyonlu Diş Çekimi", amount: 4950 },
  { id: "ozl-gomulu", code: "OZL-042", treatment: "Gömülü Diş Operasyonu", amount: 7975 },
  { id: "ozl-sinus-lifting", code: "OZL-043", treatment: "Sinüs Lifting", amount: 14465 },
  { id: "ozl-implant", code: "OZL-044", treatment: "İmplant Cerrahisi", amount: 22440 },
  { id: "ozl-implant-cikarma", code: "OZL-045", treatment: "İmplant Çıkartılması", amount: 10450 },
  { id: "ozl-zigoma", code: "OZL-046", treatment: "Zigoma İmplant", amount: 49500 },
  { id: "ozl-distasi", code: "OZL-047", treatment: "Diş Taşı Temizliği (Tek Çene)", amount: 3300 },
  { id: "ozl-kuretaj", code: "OZL-048", treatment: "Subgingival Küretaj (Tek Diş)", amount: 1870 },
  { id: "ozl-gingivoplasti", code: "OZL-049", treatment: "Gingivoplasti (Tek Diş)", amount: 3135 },
  { id: "ozl-gingivektomi", code: "OZL-050", treatment: "Gingivektomi (Tek Diş)", amount: 3245 },
  { id: "ozl-flap", code: "OZL-051", treatment: "Flap Operasyonu (Tek Diş)", amount: 5225 },
  { id: "ozl-frenektomi", code: "OZL-052", treatment: "Frenektomi / Frenetomi", amount: 7700 },
  { id: "ozl-ortodontik-fotograf", code: "OZL-053", treatment: "Ortodontik Fotoğraf", amount: 990 },
  { id: "ozl-seffaf-plak-hafif", code: "OZL-054", treatment: "Şeffaf Plak Ortodonti (Hafif)", amount: 53900 },
  { id: "ozl-seffaf-plak-orta", code: "OZL-055", treatment: "Şeffaf Plak Ortodonti (Orta)", amount: 69300 },
  { id: "ozl-seffaf-plak-agir", code: "OZL-056", treatment: "Şeffaf Plak Ortodonti (Ağır)", amount: 95700 },
  { id: "ozl-lingual-retainer", code: "OZL-057", treatment: "Lingual Retainer", amount: 9625 },
];
