import path from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const baseDirectory = path.dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory });

const config = [
  {
    ignores: [".next/**", ".next-dev/**", "node_modules/**", "tmp/**", "scripts/**"],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "react/no-unescaped-entities": "warn",
      "@next/next/no-img-element": "warn",

      // `tsc --noEmit` is the type-safety gate. The legacy modules still use
      // boundary-level `any`; treating every occurrence as a lint error hid
      // actionable findings among hundreds of non-behavioural diagnostics.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": ["warn", {
        "argsIgnorePattern": "^_",
        "varsIgnorePattern": "^_",
      }],
      "@typescript-eslint/no-unused-expressions": "error",
      // next-env.d.ts is generated by Next.js with triple-slash references.
      "@typescript-eslint/triple-slash-reference": "off",
      "@typescript-eslint/no-require-imports": "off",

      // Keep correctness-oriented consistency checks as errors. Stylistic
      // rewrites are intentionally not a production gate.
      "prefer-template": "off",
      "prefer-const": "error",
      "no-var": "error",
      "no-console": ["warn", { "allow": ["warn", "error"] }],
      "consistent-return": "off",

      // Prisma aggregate properties (_count/_sum) and browser cache globals
      // are framework contracts, not naming defects.
      "camelcase": "off",
      "no-underscore-dangle": "off",
    },
  },
];

export default config;
